In [5]:
import tensorflow as tf

In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2024-01-18 12:22:39.510670: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-18 12:22:40.651674: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-18 12:22:40.651723: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-18 12:22:40.654728: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-18 12:22:40.654766: I tensorflow/compile

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

2024-01-18 12:24:52.170276: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


array([[ 0.13159743, -0.48751974,  0.7511062 , -0.800316  ,  0.7332674 ,
        -0.41193616,  0.07018879, -0.17029972,  0.5132942 ,  0.259022  ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.09545071, 0.05139253, 0.17734885, 0.03758844, 0.17421322,
        0.05542753, 0.08976556, 0.0705776 , 0.13981314, 0.10842238]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.8926787

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

2024-01-18 12:27:24.293187: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.
2024-01-18 12:27:24.539660: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5


2024-01-18 12:27:25.580887: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f96a16e8f00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-01-18 12:27:25.580949: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3060 Ti, Compute Capability 8.6
2024-01-18 12:27:25.802119: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-01-18 12:27:26.708211: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8907
2024-01-18 12:27:27.653746: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 [==============================] - 9s 3ms/step - loss: 0.2955 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1442 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1083 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0890 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0769 - accuracy: 0.9757


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0752 - accuracy: 0.9774 - 951ms/epoch - 3ms/step


[0.0751546174287796, 0.977400004863739]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.4624447e-08, 7.7649096e-09, 1.1799369e-06, 1.0391391e-04,
        4.9864560e-11, 1.9424634e-08, 4.4084350e-12, 9.9989474e-01,
        5.6635351e-08, 9.2579299e-08],
       [1.2762010e-07, 4.1110109e-04, 9.9958092e-01, 7.7957120e-06,
        8.9088960e-15, 8.4801322e-08, 2.6806452e-08, 4.9063948e-13,
        1.2361740e-08, 4.9489617e-17],
       [1.6925134e-07, 9.9839693e-01, 2.8449329e-04, 3.0744002e-05,
        5.9950587e-05, 8.6569953e-06, 1.6206499e-05, 9.4566296e-04,
        2.5630451e-04, 8.3863705e-07],
       [9.9995852e-01, 5.7401062e-10, 1.9703573e-05, 5.0946223e-08,
        1.0912371e-06, 1.6233419e-06, 1.8220808e-05, 9.0822503e-08,
        3.4537027e-08, 7.1376411e-07],
       [1.6026388e-07, 1.2394469e-10, 1.1398064e-06, 1.7877482e-09,
        9.9682188e-01, 1.7132204e-06, 1.3829077e-06, 7.3081405e-06,
        7.6355569e-08, 3.1664509e-03]], dtype=float32)>